stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Boston.csv
    outs:
    - data/raw/Boston.csv
  split_data:
      cmd: python src/split_data.py --config=params.yaml
      deps:
      - src/split_data.py
      - data/raw/Boston.csv
      outs:
      - data/processed/train.csv
      - data/processed/test.csv
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/train_and_evaluate.py
    params:
      - estimators.LinearRegression
    metrics:
      - reports/scores.json:
          cache: false
    outs:
      - saved_models/model.joblib

  #  log_production_model:
  #   cmd: python src/log_production_model.py --config=params.yaml
  #   deps:
  #   - src/log_production_model.py