base:
  project: boston-project
  random_state: 42
  target_col: medv


data_source:
  s3_source: data_given/Boston.csv

load_data:
  raw_dataset_csv: data/raw/Boston.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  LinearRegression:
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

# webapp_model_dir: prediction_service/model/model.joblib